name: matrix workflow
on: push
jobs:
  build:
    continue-on-error: true #mesmo se algum job falhar o job continua
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: [ubuntu-latest, windows-latest]
        include: #includes adiciona novas combinações 
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: #exclui da execução a versão 12 no windows-latest
          - node-version: 12
            operating-system: windows-latest
        
     #roda em todos os sistemas operacionais citados acima no matrix strategy   
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: build project
        run: npm run build