name: Reusable deploy
on: 
  workflow_call:
    inputs:
      #input/parametro do workflow reutilizavel
      artifact-name: 
        description: name of deployable artifact file
        required: false
        default: dist
        type: string
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions-download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: output information
        run: echo "deploy & uploading"